name: Build and Push to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - run: npm ci
    - run: npm run build --if-present
