name: Build and Push to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - run: npm run build --if-present
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CLI_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_CLI_ACCESSKEY }}
        aws-region: eu-west-1
    - name: Remove old version from bucket
      run: aws s3 rm s3://rust-3d-graphics --recursive
    - name: Copy new version to bucket
      run: aws s3 cp ./dist s3://rust-3d-graphics --recursive